### PR TITLE
feat: Docker support & Poetry packaging

### PR DESCRIPTION
**Pull request by GoldToothRichards**
# Summary

1. Use [Poetry](https://python-poetry.org/docs/) for packaging and dependency management.
   - The project structure was refactored to align with the default Poetry project template .
     - Top level source code folder is now `src`.
     - Internal imports now come from the `iceberg_rest` package under `src`.
     - The `vendor` submodule is removed. Pyiceberg is installed from a git reference to the master branch in the `pyproject.toml`
    - The dependencies are separated into different _extras_ groups depending on the database flavor you want to use for your SQLCatalog.  
2. Add Docker support. The Dockerfile relies on Poetry for packing the application.
   - Uses [uvicorn](https://www.uvicorn.org/) for an ASGI server.
   - Poetry extras can be passed as a build argument to support different catalog backends/file I/O, etc.
   - Base image can be set as a build argument to support different catalog backends, file I/O, etc.
3. Add support for configuring the SQLCatalog backend using environment variables.
   - Uses [pydantic-settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/).
   - Supported variables are documented in `.env.example`.
4. Add docker-compose examples.
   - sqlite
   - sqlite/Minio
   - Postgres/Minio
   - MySQL/Minio
 5. Add development environment inside `.devcontainer`.

### CODE REVIEW

**Comment by kevinjqliu** [comment]
Thanks for the contribution. Let me take a look at these changes. 
A couple of comments from my initial skim:

1. Poetry is great 👍 . Thanks for the refactor. The `vendor` submodule is needed since there are several fixes to pyiceberg that has not been upstreamed yet. 

Screenshot 2024-06-15 at 11 07 47 AM

2. Docker support 👍 
3. Configuration using `pydantic-settings` 👍 . I've pushed a commit using `pydantic-settings` already, I'll try to merge
4. Docker-compose examples 👍 
5. Dev env in `.devcontainer` 👍

**Comment by kevinjqliu** [comment]
Thanks for the contribution @GoldToothRichards. Do you mind if I split the `.devcontainer` piece out into a separate PR?

**Comment by GoldToothRichards** [comment]
Yeah sounds good! Feel free to take whatever bits you need.

I also went ahead and put the vendor version of pyiceberg back into this PR

**Comment by kevinjqliu** [comment]
Sorry for the delay here. I accidentally deleted my `vendor` dir locally... Trying to get it back is a PAIN. 

Do you have a copy of the `vendor` dir when you pulled the repo?

**Comment by kevinjqliu** [comment]
Had to reimplement the fixes in the `vendor` dir. Got the repo in a good state now.
Thanks for your contribution!

**Pull request merged**
